# Generated by Django 5.0.3 on 2024-03-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_note_alter_post_current_user_number_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
