# Generated by Django 5.0.3 on 2024-03-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='when',
            field=models.TimeField(blank=True, default='11:00', null=True),
        ),
    ]
