# Generated by Django 5.0.3 on 2024-03-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_owner_photo_alter_post_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner_photo',
        ),
    ]
