# Generated by Django 4.2 on 2024-04-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_ownername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='when',
            field=models.TimeField(blank=True, default='202404110000', null=True),
        ),
    ]
