# Generated by Django 5.0.3 on 2024-03-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
