# Generated by Django 5.0.3 on 2024-03-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='language',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='major',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='minor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='year',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
