# Generated by Django 5.0.3 on 2024-03-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_country_account_gender_account_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
