# Generated by Django 5.0.3 on 2024-03-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
