# Generated by Django 5.0.3 on 2024-03-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_account_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emailAgree',
            field=models.BooleanField(default=True),
        ),
    ]
